### PR TITLE
README.rst -> README.md; 2.4.1 -> 2.4.2

### PR DESCRIPTION
**Pull request by DarylGrunau**
Small fixes to the setup.py file to open the proper file for the long_description, and update the version information to the most recent tag.  I was successful in writing a Spackage for PyDV, which I will commit upstream if you accept this PR.

### CODE REVIEW

**Comment by DarylGrunau** [comment]
@griffin28, I'm not sure if you get notified about this PR so I'm directly contacting you here.  Sorry if this is a duplicate!

**Comment by griffin28** [comment]
Thank you! I forgot about the setup.py file.

**Comment by griffin28** [comment]
@DarylGrunau I can add you to the PyDV Users List if you send an email to pydv-users@llnl.gov

**Comment by DarylGrunau** [comment]
Thanks a ton for merging this!  I sent an e-mail to the list you should see soon.

**Comment by DarylGrunau** [comment]
@griffin28, based upon this merge I'd like to submit a spackage upstream.  Do you feel like tagging a new release based upon this change (or, how do you prefer the spack package to fetch versions you bless?)?

**Comment by griffin28** [comment]
@DarylGrunau can you give me a call: 925.422.7178. I didn't get your email and I don't mind tagging a new release just what to understand your needs more.

**Comment by DarylGrunau** [comment]
Kevin, I left a voicemail with my telephone number.  I'd just like to be able to code a version into the spackage, e.g. 2.4.2 or 2.4.3, that corresponds to the repo at some fixed point in time that you'd really consider to be version 2.4.2 or 2.4.3.  If git clone your tag pydv-release-2.4.2, I'll miss the changes to setup.py that just got merged and the build will break.  I just need a new tag, e.g. pydv-release-2.4.3, that would include the new content so the spackage would build.

**Pull request merged**
